// <auto-generated />
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221223163935_mig_allahuekber")]
    partial class mig_allahuekber
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.About", b =>
                {
                    b.Property<int>("AboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutValueTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.DetectiveStory", b =>
                {
                    b.Property<int>("DetectiveStoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DetectiveDescription1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetectiveStoryID");

                    b.ToTable("DetectiveStories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.FindKiller", b =>
                {
                    b.Property<int>("FindKillerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FindKillerClose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindKillerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindKillerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FindKillerStatus")
                        .HasColumnType("bit");

                    b.HasKey("FindKillerID");

                    b.ToTable("FindKillers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Intro", b =>
                {
                    b.Property<int>("IntroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IntroDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntroTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntroID");

                    b.ToTable("Intros");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SceneOne", b =>
                {
                    b.Property<int>("SceneOneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SceneOneDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneOneImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneOneTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SceneOneID");

                    b.ToTable("SceneOnes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SceneTwo", b =>
                {
                    b.Property<int>("SceneTwoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SceneTwoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneTwoImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneTwoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SceneTwoID");

                    b.ToTable("SceneTwos");
                });
#pragma warning restore 612, 618
        }
    }
}
