// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.About", b =>
                {
                    b.Property<int>("AboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutValueTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Accussed1", b =>
                {
                    b.Property<int>("Accussed1ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Accussed1Close")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Accussed1ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Accussed1NameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Accussed1ID");

                    b.ToTable("Accusseds1");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Accussed2", b =>
                {
                    b.Property<int>("Accussed2ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Accussed2Close")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Accussed2ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Accussed2NameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Accussed2ID");

                    b.ToTable("Accusseds2");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.DetectiveStory", b =>
                {
                    b.Property<int>("DetectiveStoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DetectiveDescription1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetectiveStoryID");

                    b.ToTable("DetectiveStories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.FindKiller", b =>
                {
                    b.Property<int>("FindKillerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FindKillerClose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindKillerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindKillerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FindKillerStatus")
                        .HasColumnType("bit");

                    b.HasKey("FindKillerID");

                    b.ToTable("FindKillers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Intro", b =>
                {
                    b.Property<int>("IntroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IntroDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntroTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntroID");

                    b.ToTable("Intros");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Investigation1", b =>
                {
                    b.Property<int>("Investigation1ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Inv1Answer1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Answer9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inv1ChildrenNo")
                        .HasColumnType("int");

                    b.Property<string>("Inv1City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Closed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Inv1Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inv1ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1NameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Officer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv1Question9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Investigation1ID");

                    b.ToTable("Investigations1");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Investigation2", b =>
                {
                    b.Property<int>("Investigation2ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Inv2Answer1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Answer9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inv2ChildrenNo")
                        .HasColumnType("int");

                    b.Property<string>("Inv2City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Closed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Inv2Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inv2ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2NameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Officer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inv2Question9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Investigation2ID");

                    b.ToTable("Investigations2");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SceneOne", b =>
                {
                    b.Property<int>("SceneOneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SceneOneDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneOneImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneOneTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SceneOneID");

                    b.ToTable("SceneOnes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SceneTwo", b =>
                {
                    b.Property<int>("SceneTwoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SceneTwoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneTwoImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneTwoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SceneTwoID");

                    b.ToTable("SceneTwos");
                });
#pragma warning restore 612, 618
        }
    }
}
